config/routes.rb
Rails.application.routes.draw do

  get 'courses/index'

  get 'courses/show'

  get 'courses/edit'

  get 'courses/delete'

  get 'courses/update'

  get 'courses/create'

  get 'admin_activities/course'

  get 'admin_activities/lecturer'

  get 'admin_activities/student'

  get 'admin_activities/session_activities'
  
  #routes for news
  post '/create_news', to: 'news#create'
  post '/search_news', to: 'news#search'
  post '/delete_news', to: 'news#delete'
  post '/update_news', to: 'news#update'
  post '/preview_news', to: 'news#preview'
  
	
  
  #routes for lecturers 
  post '/create_lecturer', to: 'lecturers#create'
  post 'delete_lecturer', to: 'lecturers#delete'
  post '/edit_lecturer', to: 'lecturers#update'
  post '/search_lecturer', to: 'lecturers#search'
  get '/print_lecturer_password', to: 'lecturers#print_passwords'
  
  #routes for students
  post '/create_student', to: 'students#create'
  post '/edit_student', to: 'students#update'
  post '/delete_student', to: 'students#delete'
  post '/search_student', to: 'students#search'
  get '/print_student_password', to: 'students#print_passwords'

  #routes for courses
  post '/search_course', to: 'courses#search'
  post '/create_course', to: 'courses#create'
  post '/update_course', to: 'courses#update'
  post '/delete_course', to: 'courses#delete'

  #routes for admin activities
  post '/query_code', to: 'admin_activities#checkcode'
  get '/admin_index', to: 'admin_activities#index'
  get '/admin_dashboard', to: 'admin_activities#dashboard'
  get '/admin_student', to: 'admin_activities#student'
  get '/admin_course', to: 'admin_activities#course'
  get '/admin_lecturer', to: 'admin_activities#lecturer'
  get '/admin_news', to: 'admin_activities#news'
  get '/admin_session_activities', to: 'admin_activities#session_activities'

  #routes for attendance controller
  get '/course_attendance', to: 'attendances#index'
  post '/print_attendance', to: 'attendances#print'


  #routes for lectrurer results submission
  post '/scores', to: 'submit_results#scores'
  get '/submit_results', to: 'submit_results#index'
  post '/submit_results', to: 'submit_results#create'
  post '/edit_scores', to: 'submit_results#edit_scores'
  post '/edit_all_scores', to: 'submit_results#edit_all_scores'

  #routes for student to check results
  get '/check_results', to: 'results#check_results'
  post '/results', to: "results#view_student_results"

  #routes for creating user details
  get '/login_details', to: 'create_user_login_details#new'
  post '/login_details', to: 'create_user_login_details#create'
  #routes for users login
  get '/user_login', to: 'login_sessions#new'
  post '/user_login', to: 'login_sessions#create'

  #routes for admin login
  #get '/admin_index', to: 'adminsessions#index'
 # get '/admin_login', to: 'adminsessions#new'
 # post '/admin_login', to: 'adminsessions#create'
  delete '/admin_delete', to: 'adminsessions#destroy'
  
  #routes for student login
  #get '/student_login', to: 'studentsessions#new'
  #post '/student_login', to: 'studentsessions#create'
  delete '/student_logout', to: 'studentsessions#destroy'

  #routes for lecturer login
  get '/lecturer_login', to: 'lecturersessions#new'
  post '/lecturer_login', to: 'lecturersessions#create'
  delete '/lecturer_logout', to: 'lecturersessions#destroy'


  get '/visit_library', to: 'lectureractivities#library'
  get '/lecturer_notification', to: 'lecturersessions#notification'
  get '/lecture_timetable', to: 'lectureractivities#timetable'
  post '/upload', to: 'lectureractivities#upload'

  #routes for student course enrolement
  get '/create', to: 'registrations#create'
  get '/registrations', to: 'registrations#index'

  #routes for student to download and submit assignment
  post '/assignment_submit', to: 'assignment_submissions#submit'
  get '/assignment_getassignment', to: 'assignment_submissions#setassign'
  post '/assignment_getassignment', to: 'assignment_submissions#getassign'

  #routes for lecturer to create and download assignment
  post '/assignment', to: 'assignments#new'
  get '/all_assign_courses', to: 'assignments#index2'
  post '/get_assignment', to: 'assignments#getassign'

  #routes for time table
  post'/settimetable', to: 'admin_activities#set_time_table'
  get'/gettimetable', to: 'admin_activities#get_time_table'


  resources :admins
  resources :lecturers
  resources :assignment_submissions
  resources :assignments
  resources :students
  resources :news
  resources :registrations

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #These routes define the site navigation
  root 'departsite#index'
  get '/home', to: 'departsite#index'
  get '/about', to: 'departsite#about'
  get '/about', to: 'departsite#about'
  get '/alumni', to: 'departsite#alumni'

  get '/student_login', to: 'studentsessions#new'
  get '/lecturer_login', to: 'lecturersession#new'

  
end

app/controllers/admin_activities_controller.rb
class AdminActivitiesController < ApplicationController
  
  def index
  end

   def dashboard
    respond_to do|format|
        format.html{render layout:false}
        format.js
    end
   end

  def course
    @count = 0;
    @course = Course.all
	@lecturer = Lecturer.all
    respond_to do|format|
        format.html{render layout:false}
        format.js
    end
  end

 def lecturer
	@counter = 1
	@lecturers = Lecturer.all
    respond_to do|format|
		format.js
    end
  end

  def student
	@counter = 1
	@_100_level_students = Student.where('level == ?', 100)
	@_200_level_students = Student.where('level == ?', 200)
	@_300_level_students = Student.where('level == ?', 300)
	@_400_level_students = Student.where('level == ?', 400)
	@_500_level_students = Student.where('level == ?', 500)
	
    respond_to do|format|
		format.js
    end
  end

  def session_activities
    respond_to do |format|
      format.js
      format.html{render layout:false}
    end
  end

  def news
	@news = News.all
	respond_to do|format|
		format.js
    end
  end

  def checkcode
    @response =""
    @query = params[:query]
    Course.find_by(ccode: @query) ? @response = true : @response = false
    respond_to do |format|
      format.js
      format.html{render layout:false}
      format.json{render json: @response.to_json}
    end
    return @response
  end

  def set_time_table
    value = params[:value]
    day = params[:day]
    per = params[:period]
    row = params[:row].to_i
    path = "#{Rails.root}/public/time_table/time_table.json"
    file = File.new(path, 'r')
    data = JSON.parse(File.read(file))
    file.close
    if data
      data[day][per][row] = value
      temp = data.to_json
      file = File.new(path,"w")
      if file.write(temp)
        file.close
      end
    else

    end
  end

  def get_time_table
    path = "#{Rails.root}/public/time_table/time_table.json"
    file = File.new(path, 'r')
    data = File.read(file)
    file.close
    respond_to do |format|
      format.json{render json: data}
    end
  end 
end

app/helpers/admin_activities_helper.rb
module AdminActivitiesHelper
end

app/views/admin_activities/_course_menu.html.erb
<!-- courses Menu -->
<div class="row">
    <div id="course_menu">
        <div class="col-t-12 col-d-12" >
			<h1>Courses</h1>
        </div>
    <div>
</div>

app/views/admin_activities/_course_menu_old.html.erb
<!-- COURSES Menu -->
<!--<div class="row">
    <div id="course_menu">
        <div class="col-t-4 col-d-4" >
            <div class="course_menu_item" id="new_course_menu_item" data-ref="create_course_option">
                <img class = "icon"  src = ""/><br/>
                New
            </div>
        </div>
        <div class="col-t-4 col-d-4" >
            <div class="course_menu_item" id="edit_course_menu_item" data-ref="find_course_option">
                <img class = "icon" src = ""/><br/>
                Edit
            <div>
        </div>
        <div class="col-t-4 col-d-4">
            <div class="course_menu_item" id="delete_course_menu_item" data-ref="fnd_course_option">
                <img class = "icon" src = ""/><br/>
                Delete
            </div>
        </div>
    <div>
</div>-->
<div id="course_menu" class = "page my-fade">
                <!--THE OPERATIONS CONCERNING COURSES -->
                <div id = "operations" class="">
                    <div id="new_course_menu_item" data-ref="create_course_option" class = "tips">
                        Create
                    </div>
                </div>
</div>

app/views/admin_activities/_course_operations_old.html.erb
<div id="create_course" class="my-modal">
    <div id = "create_modal" class="my-modal-content">
        <div class="my-modal-header">
          <span id="cancel_create_course" class="close cancel_button" data-class="cancel_ref" data-ref = "create_cont">&times;</span>
          <h2>CREATE NEW COURSE</h2>
        </div>
        <div id="create_modal_body" class="my-modal-body">
            <div id ="create_course_option" class="course_option" data-class="display">
				<div class = "myrow">
                    <div class = "col-t-12 col-d-12 no-padding">
                        <div class="handle white_bg">
                            <% if flash[:success] %>
                                <div class = 'success'><%= flash[:success] %></div>
                            <% end %>
                            <% if flash[:error] %>
                                <div data-class="notice" class = 'error'></div>
                            <% end %>
                            <%= form_for :create_course,  url:create_course_path, remote:true, html: {id: "create_form"} do|f| %>
							<div id="course-fields0" class="fields_div">
								<span id="new-course-error0" class ='error'></span>
								<%= f.label "Code : ",  id: 'create_ccode', class:"modal_label" %>
								<%= fields_for :code do|fc| %>
									<%= fc.text_field :ccode0, id: 'create_ccode_field', class: 'modal_inputs', maxlength: '7'%>
								<% end %>
								
								
								<%= f.label "Title : ",  id: 'create_ctitle', class:"modal_label" %>
								<%= fields_for :title do|ft| %>
									<%= ft.text_field :ctitle0,  id: 'create_ctitle_field', class: 'modal_inputs' %>
								<% end %>

								<%= f.label "Units : ",  id: 'create_unit', class:"modal_label" %>
								<%= fields_for :units do|fu| %>
									<%= fu.text_field :units0,  id: 'create_units_field', class: 'modal_inputs', maxlength: '2' %>
								<% end %>
								
								<%= f.label "Level : ",  id: 'create_level', class:"modal_label" %>
								<%= fields_for :level do|fs| %>
									<%= fs.select :level0, ["100", "200", "300", "400", "500"], class: 'modal_inputs' %>
								<% end %>

								<%= f.label"Status : ",  id: 'create_status', class:"modal_label" %>
								<%= fields_for :status do|fs| %>
									<%= fs.select :status0, ["borrowed", "spill over", "elective"] %>
								<% end %>

								<%= f.label "Semester : ",  id: 'create_semester', class:"modal_label" %>
								<%= fields_for :semester do|fs| %>
									<%= fs.radio_button :semester0, "0",  class: 'modal_inputs' %><%= f.label "first", class: "status modal_label" %>
									<%= fs.radio_button :semester0, "1", class: 'modal_inputs' %><%= f.label "second", class: "status modal_label" %><div id="addrow" class="custom_button", data-row="new_row", onclick="add()">+</div><div id="remrow" class="custom_button", data-row="del_row">-</div><br/>
								<% end %>
							</div>
							<div id ="append">
                            </div>

                            <%= f.submit :create, id: 'create_course' %>
                            <% end %>
                        </div>
                </div>
        </div>
    </div>
        </div>
</div>

app/views/admin_activities/_general_student_js_script.js.erb
function generate100LevelStudentsTable(){
		return '<table id="lectrers"><tr><th>S/N</th><th>Mat. No.</th><th>Name</th><th>Sex</th><th>Nationality</th><th>State of Origin</th><th>L.G.A</th><th>E-mail</th><th>Phone Number</th></tr><% @counter = 1 %><% @_100_level_students.each do|student| %><tr class="student_details" id="<%= student.id %>"><td><%= @counter %></td><td><%= student.matno %></td><td><%= student.sname %> <%=student.fname %> <%= student.student_othername.othernames if student.student_othername %></td><td><%= student.sex %></td><td><%= student.nationality %></td><td><%= student.state_of_origin %></td><td><%= student.lga %></td><td><%= student.email %></td><td><%= student.phone %></td></tr><% @counter +=1 %><% end %></table>';
}


//display student details when a row is clicked
function trig_student_edit(){
	//this is a duplicated function, a copy is in create.js.erb
	$("tr").click(function(){
		var lec = {};
		<% @students = Student.all %>
		<% @students.each do|student| %>
			if (this.id == "<%= student.id %>"){
				$("#edit_id_field").val("<%= student.id %>");
				$("#edit_mat_no_field").val("<%= student.matno %>");
				$("#edit_sname_field").val("<%= student.sname %>");
				$("#edit_fname_field").val("<%= student.fname %>");
				$("#edit_sex_field").val("<%= student.sex %>");
				$("#edit_state_of_origin_field").val("<%= student.state_of_origin %>");
				$("#edit_lga_field").val("<%= student.lga %>");
				$("#edit_nationality_field").val("<%= student.nationality %>");
				$("#edit_religion_field").val("<%= student.religion %>");
				$("#edit_email_field").val("<%= student.email %>");
				$("#edit_phone_field").val("<%= student.phone %>");
				$("#edit_othernames_field").val("<%= student.student_othername.othernames if student.student_othername %>");
				$(":text").attr("disabled","true");
				$("#edit_student_form_fields").css("display","inline-block");
				$("#edit_student_button").css("display","none");
				$("#edit_password_field").css("display","none");
				$("#edit_cont1").css("display", "block");
			}

		<% end %>
	});
}

function fill(){
	alert("hello world");
}

app/views/admin_activities/_lecturer_operations.html.erb
<div class="row">
    <div class="col-t-4 col-d-4"><button id="activate_create_lecturer_modal" onclick="createUser();">Create Single</button></div>
    <div class="col-t-4 col-d-4"><button id="activate_lecturer_multiple">Create Multiple From File</button></div>
		<%= link_to "Print generated Passwords", print_lecturer_password_path, target:"_blank" %>
</div>

<!--CREATE OPERATIONS -->
<div class="row">
    <div id="create_cont" class="my-modal">
        <div id ="create_lecturer_option" class="lecturer_option" data-class="disply">
            <!-- form for lecturer creation-->
            <div class = "row">
                <div class = "col-t-2 col-d-2"></div>
                    <div class = "col-t-8 col-d-8 modal-content zoom-in">
						<span id="cancel_create_lect" class="cancel_button" data-class="cancel_ref" data-ref = "create_cont">&times;</span>
                        <h4>CREATE NEW LECTURER</h4>
                            <div id="create_error" data-class="notice" class = "create_error msg"></div>
                            <%= form_for :create_lecturer, url:create_lecturer_path, remote:true, html:{id:"create_lecturer_form"} do|f| %>
                            <%= f.label "Staff ID",  id: 'create_staff_id' %>
                            <%= f.text_field :staff_id, id: 'create_staff_id_field' %><br/>
                            <%= f.label "Surname",  id: 'create_sname' %>
                            <%= f.text_field :sname,  id: 'create_sname_field' %><br/>
                            <%= f.label :"First Name",  id: 'create_fname' %>
                            <%= f.text_field :fname,  id: 'create_fname_field' %><br/>
                            <%= f.label :"Other Names",  id: 'create_other_names' %>
                            <%= f.text_field :othernames,  id: 'create_other_names_field' %><br/>
                            <%= f.label :sex,  id: 'create_sex' %>
                            <%= f.text_field :sex,  id: 'create_sex_field' %><br/>
                            <%= f.label :nationality,  id: 'create_nationality' %>
                            <%= f.text_field :nationality,  id: 'create_nationality_field' %><br/>
                            <%= f.label :"State Of Origin",  id: 'create_state_of_origin' %>
                            <%= f.text_field :state_of_origin,  id: 'create_state_of_origin_field' %><br/>
                            <%= f.label :"LGA",  id: 'create_lga' %>
                            <%= f.text_field :lga,  id: 'create_lga_field' %><br/>
                            <%= f.label :religion,  id: 'create_religion' %>
                            <%= f.text_field :religion,  id: 'create_religion_field' %><br/>
                            <%= f.label :email,  id: 'create_email' %>
                            <%= f.text_field :email,  id: 'create_email_field' %><br/>
                            <%= f.label :phone,  id: 'create_phone' %>
                            <%= f.text_field :phone,  id: 'create_phone_field' %><br/>
                            <%= f.submit :create, id: 'create_lecturer' %><div id="cancel_create_lect_form" class="button" data-class="cancel_ref" data-ref="create_cont">Cancel</div>
                        <% end %>
                    </div>
                <div class = "col-t-2 col-d-2"></div>
            </div>
        </div>
    </div>
	
    <!--END OF CREATE OPERATIONS -->

    <!--EDIT OPERATIONS -->
	
    <!-- Table for courses is placed in this div -->
	<div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">

                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <%= form_for :search, remote: true, url:search_lecturer_path, html:{id:"search_form"} do|f| %>
                                search : 
									<%= f.search_field :lecturer %>
									<%= f.submit :submit, style:"display:none", id:"search_lecturer_submit" %>
								<% end %>
                            </div> 
                            <div class="panel-body">
							Click on any row to edit the lecturer's details
                                <div id="table_for_lecturers" class="table-responsive">
                                    
                                </div>                               
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /. ROW  -->
            </div>
	
	
	
	<div id="edit_cont1" class="my-modal">		
		  <div id = "edit_modal" class="my-modal-content">
        <div class="my-modal-header">
         <span id="cancel_edit_lect" class="cancel_button" data-class="cancel_ref" data-ref = "edit_cont1">&times;</span>
          <h2>Lecturer Information</h2>
        </div>
        <div id = "edit_modal_body" class="my-modal-body">
        <div id = "find_course_option" class="course_option" data-class="display">
           <div class = "row">
                <div class = "col-t-2 col-d-2"></div>
                    <div class = "col-t-8 col-d-8">
                            <div class="handle white_bg">
								<div id="edit_error" data-class="notice" class = "edit_error msg"></div>
								<%= form_for :edit_lecturer, url:edit_lecturer_path, remote:true, html:{id:"edit_lecturer_form"} do|f| %>
								<%= f.hidden_field :id, id: "edit_id_field" %>
								<%= f.label "Staff ID",  id: 'edit_staff_id' %>
								<%= f.text_field :staff_id, id: "edit_staff_id_field" %><br/>
								<%= f.label "Surname",  id: 'edit_sname' %>
								<%= f.text_field :sname,  id: 'edit_sname_field' %><br/>
								<%= f.label :"First Name",  id: 'edit_fname' %>
								<%= f.text_field :fname,  id: 'edit_fname_field' %><br/>
								<%= f.label :"Other Names",  id: 'edit_other_names' %>
								<%= f.text_field :othernames,  id: 'edit_othernames_field' %><br/>
								<%= f.label :sex,  id: 'edit_sex' %>
								<%= f.text_field :sex,  id: 'edit_sex_field' %><br/>
								<%= f.label :nationality,  id: 'edit_nationality' %>
								<%= f.text_field :nationality,  id: 'edit_nationality_field' %><br/>
								<%= f.label :"State Of Origin",  id: 'edit_state_of_origin' %>
								<%= f.text_field :state_of_origin,  id: 'edit_state_of_origin_field' %><br/>
								<%= f.label :"LGA",  id: 'edit_lga' %>
								<%= f.text_field :lga,  id: 'edit_lga_field' %><br/>
								<%= f.label :religion,  id: 'edit_religion' %>
								<%= f.text_field :religion,  id: 'edit_religion_field' %><br/>
								<%= f.label :email,  id: 'edit_email' %>
								<%= f.text_field :email,  id: 'edit_email_field' %><br/>
								<%= f.label :phone,  id: 'edit_phone' %>
								<%= f.text_field :phone,  id: 'edit_phone_field' %><br/>
								<%= f.submit :finish, id: "edit_lecturer_button" %>
								<div id="edit_lecturer_form_fields" class="button">Edit</div>
								<%= f.submit :delete, id:"delete_lecturer_form_fields", class:"button" %>
								<div id="cancel_edit_lect_form" class="button" data-class="cancel_ref" data-ref="edit_cont1">Ok</div>
							
								<% end %>
                            </div>
                    </div>
                <div class = "col-2"></div>
            </div>
            </div>
        </div>
      </div>
    </div>
    <!--END OF EDIT OPERATIONS -->
	
	<div id="alert-modal" class="my-modal">
		<div class="alert-box">
			<div class="alert-head">
			 <span id="close-alerts" style="font-size: 18pt; margin-right: 8px;" class="cancel_button" data-class="cancel_ref" data-ref = "edit_cont1">&times;</span>
			  <h4 id="alert-h-text" style="margin-top: 0px; text-align:center;">Success</h4>
			</div>
			<div id="alert-body" class="alert-body">
				1 Student succefully added to the database
			</div>
			<div class="alert-footer">
				<div id="close-alert">Close</div>
			</div>
		</div>
	</div>
	
	
	
</div>

app/views/admin_activities/_news_menu.html.erb
<!-- students Menu -->
<div class="row">
    <div id="student_menu">
        <div class="col-t-12 col-d-12" >
			<h1>News </h1>
        </div>
    <div>
</div>

app/views/admin_activities/_news_operations.html.erb
<div class="row">
    <div class="col-t-4 col-d-4"><button id="activate_create_news_modal" onclick="createUser();">Create Single</button></div>
    <div class="col-t-4 col-d-4"><button id="activate_news_multiple">Create Multiple From File</button></div>
</div>
<div id="edit_success" class = "edit_success msg"></div>
<div id="create_success" class = "create_success msg"></div>

<!--CREATE OPERATIONS -->
<div class="row">
    <div id="create_cont" class="my-modal">
        <div id ="create_news_option" class="news_option" data-class="disply">
            <!-- form for news creation-->
            <div class = "row">
                <div class = "col-t-2 col-d-2"></div>
                    <div class = "col-t-8 col-d-8 modal-content zoom-in">
						<span id="cancel_create_lect" class="cancel_button" data-class="cancel_ref" data-ref = "create_cont">&times;</span>
                        <h4>CREATE NEWS</h4>
                            <div id="create_success" class = "create_success msg"></div>
                            <div id="create_error" data-class="notice" class = "create_error msg"></div>
								<%= form_for :create_news, url:"/create_news.js", remote: true, multipart: true, authenticity_token:true do|f| %>
                            <%= f.label "News Heading",  id: 'create_news_heading' %>
                            <%= f.text_field :heading, id: 'create_news_heading_field' %><br/>
                            <%= f.label "Body",  id: 'create_content' %>
                            <%= f.text_area :content,  id: 'create_news_content_field', class:"news_content" %><br/>
                            <%= f.label :"News Photo",  id: 'create_news_photo' %>
                            <%= f.file_field :image,  id: 'create_news_photo_field' %><br/>
							<div id="select_news_image">Upload Image</div>
                            <%= f.submit :create, id: 'create_news' %><div id="cancel_create_lect_form" class="button" data-class="cancel_ref" data-ref="create_cont">Cancel</div>
                        <% end %>
                    </div>
                <div class = "col-t-2 col-d-2"></div>
            </div>
        </div>
    </div>
	
    <!--END OF CREATE OPERATIONS -->

    <!--EDIT OPERATIONS -->
	
    <!-- Table for courses is placed in this div -->
	<div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">

                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <%= form_for :search, remote: true, url:search_news_path, html:{id:"search_form"} do|f| %>
                                search : 
									<%= f.search_field :news %>
									<%= f.submit :submit, style:"display:none", id:"search_news_submit" %>
								<% end %>
                            </div> 
                            <div class="panel-body">
							Click on any row to edit the news's details
                                <div id="table_for_news" class="table-responsive">
                                    
                                </div>                               
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /. ROW  -->
            </div>
	
	
	
	<div id="edit_cont1" class="my-modal">		
		  <div id = "edit_modal" class="my-modal-content">
        <div class="my-modal-header">
         <span id="cancel_edit_lect" class="cancel_button" data-class="cancel_ref" data-ref = "edit_cont1">&times;</span>
          <h2>Edit News</h2>
        </div>
        <div id = "edit_modal_body" class="my-modal-body">
        <div id = "find_course_option" class="course_option" data-class="display">
           <div class = "row">
                <div class = "col-t-2 col-d-2"></div>
                    <div class = "col-t-8 col-d-8">
                            <div class="handle white_bg">
                                   <div id="edit_success" class = "edit_success msg"></div>
								<div id="edit_error" data-class="notice" class = "edit_error msg">Hello error</div>
								<%= form_for :edit_news, url:preview_news_path, remote:true, multipart: true, authenticity_token:true do|f| %>
								<%= f.hidden_field :id, id: "edit_id_field" %>
								<%= f.label "Heading",  id: 'edit_heading' %>
								<%= f.text_field :heading, id: "edit_news_heading_field" %><br/>
								<%= f.label "Content",  id: 'edit_news_content' %>
								<%= f.text_area :content,  id: 'edit_news_content_field', class:"news_content" %><br/>
								<%= image_tag "", id:"news_image", html:{width: "20%", height:"30%"} %>
								<%= f.label :"News Photo",  id: 'edit_photo' %>
								<%= f.file_field :image,  id: 'edit_news_photo_field' %>
								<%= f.submit :finish, id: "edit_news_button" %>
								<div id="edit_news_form_fields" class="button">Edit</div>
								<%= f.submit :delete, id:"delete_news_form_fields", class:"button" %>
								<div id="cancel_edit_lect_form" class="button" data-class="cancel_ref" data-ref="edit_cont1">Ok</div>
							
								<% end %>
                            </div>
                    </div>
                <div class = "col-2"></div>
            </div>
            </div>
        </div>
      </div>
    </div>
    <!--END OF EDIT OPERATIONS -->
</div>

app/views/admin_activities/dashboard.html.erb
 <% content_for :admin_header do %>
    <div class = "div col-t-3 col-d-2" id = "admin-head">
        <%= image_tag "ndu_logo.png" %>
        <div id = "navs">
            <ul class="na">
                <li class = "adminli" id = "dash"><%= image_tag('navs/course.svg', class: 'icon icon-img')%><%= link_to "Dashboard", admin_path, remote:true %></li>
                <li class = "adminli" id = "lect"><%= image_tag('navs/lecturer.svg', class: 'icon icon-img')%><%= link_to "Lecturer", admin_lecturer_path, remote:true %></li>
                <li class = "adminli" id = "stud"><%= image_tag('navs/student.svg', class: 'icon icon-img')%><%= link_to "Student", admin_student_path, remote:true %></li>
                <li class = "adminli" id = "cos"><%= image_tag('navs/course.svg', class: 'icon icon-img')%><%= link_to "Courses",id:"coss", admin_course_path, remote: true %></li>
                <li class = "adminli" id = "new"><%= image_tag('navs/news.svg', class: 'icon icon-img')%><%= link_to "News", admin_news_path, remote:true %></li>
                <li class = "adminli" id = "session_act"><%= image_tag('navs/news.svg', class: 'icon icon-img')%><%= link_to "Session Activities", admin_session_activities_path, remote:true %> </li>
            </ul>
        </div>
    </div>
    <% end %>

    <div class = "div col-t-9 col-d-10" id="container" >
    </div>
    <div id="load" class="modal">
        <div class="loader"></div>
    </div>